import random
from faker.providers import BaseProvider

class ReceitaProvider(BaseProvider):
    def receita_titulo(self):
        titulo = [
            'Cheesecake com calda de morango',
            'Cheesecake de paçoca',
            'Chester recheado com farofa',
            'Chips de banana',
            'Chips de maçã',
            'Chuchu empanado',
            'Churros crocantes',
            'Chutney de abacaxi',
            'Cocada de mandioca',
            'Colomba pascal',
            'Cogumelos pais, shimeji e shitake',
            'Contra filé à francesa',
            'Contra filé com molho de gorgonzola',
            'Abóbora assada',
            'Abobrinha à parmegiana recheada',
            'Abobrinha marinada',
            'Abacaxi ao vinho',
            'Almôndegas de ervilha',
            'Almôndegas de grão de bico',
            'Aperitivo de pepino',
            'Arroz branco',
            'Arroz com frutas cristalizadas sem uvas passas',
            'Arroz com linguiça na cachaça',
            'Pão recheado com ingredientes de pizza',
            'Pastel de pernil',
            'Palmito pupunha assado',
            'Palmito pupunha com quinoa',
            'Pavê com creme belga',
            'Pavê de chocolate com paçoca e pé de moleque',
            'Peixe grelhado, cozido e assado',
            'Peixe com creme de vinho, mexilhões e batatas assadas',
            'Peixe com crosta de coco e cuscuz de ervas',
            'Peixinho vegano empanado com tofu',
            'Pepino com coalhada',
            'Pera assada',
            'Arroz com lula',
            'Arrumadinho',
            'Atoladinho de carne seca',
            'Biscoitinho amanteigado',
            'Biscoitinho de queijo',
            'Biscoito de Natal',
            'Brigadeiro de açaí',
            'Brigadeiro de cream cheese recheado com doce de leite',
            'Brigadeiro de amendoim',
            'Quiabo sequinho',
            'Quibe recheado com queijos',
            'Quiche de legumes',
            'Quiche francesa com bacon',
            'Brigadeiro tradicional',
            'Bruschettas de abobrinha e espinafre',
            'Bruschettas caprese']
 
        return random.choice(titulo)
 